#spring会从classpath下的/config目录或者classpath的根目录查找application.properties或application.yml。
#/config优先于classpath根目录
static-locations: classpath:/static/,classpath:/views/templates
cache-period: 0
management:
  security:
    enabled:false
server:
  port: 8080
  tomcat:
    max-threads:800
    uri-encoding:UTF-8
    access-log-enabled:true
logging:
  #logback log dir
  path: /opt
  file: zconsole.log
  level.*: DEBUG
